server:
  port: 8080

spring:
  profiles:
    active:
      - dev
  #数据源的配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 60000
      max-lifetime: 1800000
      pool-name: DataSourceHikariCP
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#mybatis配置，不能放在spring节点下
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.liaocx.api.model.domain  # 注意：对应实体类的路径
  configuration:
    jdbc-type-for-null: null
    cache-enabled: true
    call-setters-on-nulls: true

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
