server:
  port: 8080

spring:
  profiles:
    active:
      - dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: manuter0520
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#mybatis配置，不能放在spring节点下
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.liaocx.model.domain  # 注意：对应实体类的路径
  configuration:
    jdbc-type-for-null: null
    cache-enabled: true
    call-setters-on-nulls: true

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
